#!/bin/bash
root="/home/davidv7/Documents/dots/"
cd "$HOME" || exit 1
cp -R "$HOME/.config/herbstluftwm/" "$root"
cp -R "$HOME/.config/dunst/" "$root"
cp -R "$HOME/.config/termite/" "$root"
cp -R "$HOME/.config/nvim/" "$root"
cp -R "$HOME/.config/rofi/" "$root"
cp -R "$HOME/.config/music.md" "$root"
cp -R "$HOME/.config/polybar" "$root"
cp -R "$HOME/.zshrc" "$root"
cp -R "$HOME/.zsh/" "$root"
cp -R "$HOME/.zpreztorc" "$root"
cp -R "$HOME/.zprezto/" "$root"
cp -R "$HOME/.config/wallpaper.jpg" "$root"
cp -R "$HOME/.config/shows.md" "$root"
cp -R "$HOME/.config/books.md" "$root"
# DOOM EMACS
cp -R "$HOME/.doom.d" "$root"
cp -R "$HOME/.emacs.d" "$root"
cp -R "$HOME/.tmux.conf" "$root"

# KDE

dest="$HOME/Documents/dots/KDE/"
cp -R "$HOME/.config/kdeglobals" "$dest"
cp -R "$HOME/.config/kglobalshortcutsrc" "$dest"
cp -R "$HOME/.config/khotkeysrc" "$dest"
cp -R "$HOME/.config/konsolerc" "$dest"
cp -R "$HOME/.config/konversationrc" "$dest"
cp -R "$HOME/.config/kwinrc" "$dest"
cp -R "$HOME/.config/kwinrulesrc" "$dest"

cp -R "$HOME/.config/dolphinrc" "$dest"
cp -R "$HOME/.local/share/konsole/" "$dest"
cp -R "$HOME/.local/share/yakuake/" "$dest"



# Dumb scripts
#
scripts="$HOME/Documents/dots/Scripts"

cp -R "HOME/Documents/Scripts/" "$scripts"
